alchemistry/alchemlyb

src/alchemlyb/estimators/ti_.py

Error calculations are not currently implemented in the TI estimator.

Implement trapezoidal rule errors for TI

---

.travis.yml

I'm getting failures of some of the subsamplers on my local machine
under Python 3.6. It's time we add this to the Travis CI checks to see
if this is the culprit, but also to test against latest Python.

Added python 3.6 to travis-ci

---

src/alchemlyb/parsing/gmx.py
src/alchemlyb/tests/parsing/test_gmx.py
src/alchemlyb/tests/test_fep_estimators.py
src/alchemlyb/tests/test_ti_estimators.py

Modified gmx parser to handle expanded ensemble simulation data. Original parser relies on the state being disclosed in the subtitle line of the dhdl.xvg, which is not the case in expanded ensemble datasets. Instead, the states are referenced in an additional column (Thermodynamic state). Additions use this column in cases where the state is not available in the subtitle line.

Issue 14 expanded ensemble parser

---

docs/parsing/alchemlyb.parsing.amber.rst
src/alchemlyb/parsing/amber.py
src/alchemlyb/tests/parsing/test_amber.py

Fixes #42 
This pull request adds support for amber mbar parsing for amber .out  files by using the [extract_u_nk](https://github.com/alchemistry/alchemlyb/blob/amber-mbar-parse/src/alchemlyb/parsing/amber.py#L250) function, which I wrote to primarily mimic the output format of the [extract_u_nk](https://github.com/alchemistry/alchemlyb/blob/amber-mbar-parse/src/alchemlyb/parsing/gmx.py#L15) gromacs function. 
A [test_u_nk](https://github.com/alchemistry/alchemlyb/blob/amber-mbar-parse/src/alchemlyb/tests/parsing/test_amber.py#L35) function was also added to [test_amber.py](https://github.com/alchemistry/alchemlyb/blob/amber-mbar-parse/src/alchemlyb/tests/parsing/test_amber.py). I am now working on adding a minimal test example to [alchemtest](https://github.com/alchemistry/alchemtest).

amber mbar parser

---

src/alchemlyb/parsing/amber.py

As explained in https://github.com/alchemistry/alchemlyb/issues/66 the amber parser does not work in Python 3.7.
These changes should fix this.
See https://www.python.org/dev/peps/pep-0479/#sub-proposal-decorator-to-explicitly-request-current-behaviour

Make amber parser compatible with python 3.7

---

.travis.yml

Requires us to use `dist: xenial` (Ubuntu 16.04) to add this Python version to the test matrix.

Set Travis CI to test against Python 3.7

---

src/alchemlyb/parsing/gmx.py
src/alchemlyb/tests/parsing/test_gmx.py
src/alchemlyb/tests/test_preprocessing.py

As explained in https://github.com/alchemistry/alchemlyb/issues/59 The current parser assumes U and pV to be given in the second respectively last column - which is not very robust.
With these changes the parser adds them to the potential differences only when they are given. 
Moreover I am interested if these changes pass the tests.

Add pV and U to reduced potential when they are given

---

src/alchemlyb/estimators/ti_.py
src/alchemlyb/tests/test_ti_estimators.py

Sorry for messing up https://github.com/alchemistry/alchemlyb/pull/58.
In summary: I believe, that the TI error estimation in alchemlyb does not reproduce the value that alchemical-analysis calculates.
This PR should change the TI error estimation such that it reproduces the value alchemical-analysis calculates.

Correct TI error estimation II

---

src/alchemlyb/parsing/gmx.py
src/alchemlyb/parsing/util.py

pd.read_csv() shows the same behavior building pandas Dataframe with better performance. Parsing header lines remain the same but with `bytes` reading, instead of `text` mode.

gmx parser (_extract_dataframe) using pd.read_csv for performance

---

src/alchemlyb/parsing/gmx.py

Some of our datasets, such as [`alchemtest.gmx.benzene`](https://github.com/alchemistry/alchemtest/tree/master/src/alchemtest/gmx/benzene), feature duplicate columns in their data files. Previously this was handled after initial parsing with `pandas.read_csv`, but as of the latest `pandas` release this function disallows duplicate column names on entry.
We now mark duplicate column names before entry into `pandas.read_csv`, and we filter these duplicate columns from the resulting dataframe after this initial parsing.

gmx parsers now drop duplicate columns

---

src/alchemlyb/parsing/gmx.py

This is follow-up work from #86. We don't want redundancy in duplicate removal here if we don't expect it to be necessary, as this can result in silently dropping things unintentionally or make issues harder to debug.

Removed redundant duplicate removal from gmx u_nk parser

---

CHANGES
setup.py
src/alchemlyb/estimators/mbar_.py

We need an explicit `return_theta=True` call now, as before this was implicitly working.
Also switched to using a list for alchemlyb.estimators.MBAR.method, as this is in line with the stated docs for inputs to pymbar.MBAR (we were using a tuple).
We have set the install requirements in setupy.py to now have `pymbar==3.0.5` to ensure users are staying up to the latest version, as we intend to track pymbar's development carefully.

Changes in light of upstream pymbar 3.0.5

---

CHANGES
src/alchemlyb/preprocessing/subsampling.py

Removed redundant lines for calculating statistical inefficiency. 
For more information, please see Issue #96. Thank you.

Removed redundant lines for calculating statistical inefficiency

---

environment.yml
readthedocs.yml

RTD fails to build, probably because we added matplotlib to the dependencies.
EDIT: mpl is ok but the Python version needs to be > 3.5 (which I already did with the bump to 3.7)

update environment.yml with matplotlib and python 3.7

---

CHANGES
src/alchemlyb/preprocessing/subsampling.py
src/alchemlyb/tests/test_preprocessing.py

fix #116 
This PR uses the new test file from https://github.com/alchemistry/alchemtest/pull/41 so won't succeed until that one is merged.

allow statistical_inefficieny to handle multi-index timeseries

---

CHANGES
src/alchemlyb/preprocessing/subsampling.py
src/alchemlyb/tests/test_preprocessing.py

Add sort and remove duplication to statistical_inefficiency

---

CHANGES
setup.py
src/alchemlyb/estimators/ti_.py

Fix #147 
Due to https://github.com/pandas-dev/pandas/issues/42433, this will need some fix from upstream.
I have done a patch to fix the problem.

Fix pandas 1.3/1.4 support

---

.github/workflows/ci.yaml
CHANGES
setup.py

- update CHANGES
- update workflow to test all supported Python versions and OS

prepare for release 0.5.0

---

CHANGES
src/alchemlyb/estimators/mbar_.py
src/alchemlyb/tests/test_fep_estimators.py

Currently, at least `maximum_iterations` is not really being used during the MBAR solver.
So I changed the MBAR to make sure that it is taken into account as is suggested in https://github.com/choderalab/pymbar/issues/419#issuecomment-803714103.
Note the doc says other things though https://pymbar.readthedocs.io/en/master/mbar.html.
I cannot write a test to test this as `pymbar.mbar.MBAR` doesn't have a public attribute that echoes this assignment.
It is hard to raise an issue either as the bug will show itself when MBAR didn't converge within the default 250 iterations and most of the calculations converge in less than 250 iterations.

Make it that the MBAR will take in maximum_iterations argument.

---

CHANGES
docs/api_principles.rst
src/alchemlyb/tests/test_visualisation.py
src/alchemlyb/visualisation/dF_state.py

- for #164 
- CHANGES fixes
- miscellaneous last minute fixes
- visualisation.df_state.plot_dF_state() now correctly raises ValueError instead of NameError when incorrect orientation keyword argument is supplied
- close figures in vsualisation tests to avoid warnings for too many open figures
- update API docs with workflow mission statement #160

prepare 0.5.1 release

---

CHANGES
src/alchemlyb/estimators/ti_.py

fix deprecated pandas level use

---

.github/workflows/ci.yaml
.github/workflows/deploy.yaml
AUTHORS
CHANGES
setup.cfg
setup.py

Fixes #193 
Work done in this PR:
- two small changes to setup.py and setup.cfg to enforce python>=3.7 and prevent universal wheels (which are meant to also work with py2) from being built.
- Added automatic deployment to pypi on release, as per: https://github.com/MDAnalysis/GridDataFormats/blob/master/.github/workflows/deploy.yaml (I'm happy saying that bit of code is under BSD-3 if that works with you @orbeckst)

Set a strict python minimum version for install, add automated pypi deployment

---

CHANGES
src/alchemlyb/parsing/amber.py
src/alchemlyb/tests/parsing/test_amber.py
src/alchemlyb/tests/test_fep_estimators.py
src/alchemlyb/tests/test_ti_estimators.py
src/alchemlyb/tests/test_workflow_ABFE.py

This PR addresses issue #225, now:
- we require ```T``` in input for the parser
- we still read ```temp0``` from AMBER output
- the WARNING about non-constant T simulation is now a WARNING (the check could also be removed)
- the parser raises a WARNING if ```temp0 != T``` (two new tests now assert that)
- now the tests in ```test_amber.py``` use the correct  T=298.0

AMBER parser now compare user-provided T with what's read from AMBER files

---

CHANGES
src/alchemlyb/parsing/amber.py
src/alchemlyb/tests/parsing/test_amber.py

This PR removes the useless function `any_none()` which does the same work as an `if None in`, and the relative test is removed. 
This was suggested in issue #236.
I'm not introducing a check for `mbar==None`, maintaining the logic as before.

replaced useless function "any_none()" with a check for "None in"

---

CHANGES
src/alchemlyb/tests/test_workflow_ABFE.py
src/alchemlyb/workflows/abfe.py

If not explicitly set, AMBER will not generate the dHdl file. (I don't know if the u_nk will be written by default but I got a complain that workflow cannot be used to process their amber output, which doesn't have dhdl data). Currently, the ABFE workflow will attempt to read both dHdl and u_nk. This PR will make it such that if no TI estimator is chosen, the workflow will not attempt to read the dHdl.
I have also removed the ignore_warnings in the read file stage as maintaining it and having it to be clever enough to solve all the dumb user issues seems to be too much.

ABFE workflow will not read dHdl file if no TI estimator is choosen

---

docs/parsing.rst
src/alchemlyb/tests/parsing/test_namd.py

Just a couple of things that I forgot about:
- added the description of `extract` to the main `parsers` page in the documentation
- the test in test_namd.py now properly tests if 'dHdl' is not set when calling `extract`

Add extract description in docs

---

CHANGES
docs/preprocessing/alchemlyb.preprocessing.subsampling.rst
src/alchemlyb/preprocessing/subsampling.py
src/alchemlyb/tests/__init__.py
src/alchemlyb/tests/test_preprocessing.py
src/alchemlyb/tests/test_workflow_ABFE.py
src/alchemlyb/workflows/abfe.py

The 'dhdl' method in `u_nk2series` will just take the column that is the same as the current lambda, which sometimes will give you a list of zero and makes no sense at all. This PR will remove this method and change the default `dE`.
This PR also rename the 'dhdl_all' to 'all' as the name 'dhdl_all' does not make sense when working on `u_nk2series`.

Remove the 'dhdl' method in decorrelating the u_nk

---

CHANGES
src/alchemlyb/tests/test_visualisation.py
src/alchemlyb/visualisation/convergence.py

Currently the plot_convergence demand the input dataframe to have forward_error and backward_error. This PR makes these two input optional. So when these two columns are not present in the input dataframe, no errorbar will be plotted.
I have not touched the array input as we will deprecate them in #247.
A final_error keyword has been added to deal with the case where error is not provided and the user wish to plot the error of the final estimate.
Fix the issue where when too many data points are included, the x-axis will be too crowded.

Make the error optional for plot_convergence

---

.github/workflows/ci.yaml

- fix #257 
- temporary fix (reverse once pytest-xdist works again)

temporarily disable pytest-xdist

---

CHANGES
src/alchemlyb/parsing/amber.py
src/alchemlyb/tests/parsing/test_amber.py

Now `file_validation` will rise `ValueError` exceptions when errors/inconsistencies in the file are found, instead of just ignoring the problem. The tests are updated, but I found an error in a test file, which I addressed in a recent PR (until the alchemtest PR is accepted this PR will not have 100% success on the tests).

Raise except instead of continuing

---

CHANGES
src/alchemlyb/tests/test_visualisation.py
src/alchemlyb/visualisation/convergence.py
src/alchemlyb/visualisation/dF_state.py
src/alchemlyb/visualisation/ti_dhdl.py

Fix #247
Default the unit in `plot_dF_state` , `plot_convergence` and `plot_ti_dhdl` to None.
Remove the array input in `plot_convergence`.
I have fixed the issue here @DrDomenicoMarson

Default the plotting unit to None

---

docs/estimators/alchemlyb.estimators.BAR.rst
docs/estimators/alchemlyb.estimators.MBAR.rst
docs/references.rst
src/alchemlyb/estimators/bar_.py
src/alchemlyb/estimators/mbar_.py
src/alchemlyb/preprocessing/subsampling.py

- MBAR citation
- BAR citation
- equilibrium_detection citation

added citations

---

.github/workflows/ci.yaml
CHANGES
src/alchemlyb/parsing/amber.py
src/alchemlyb/tests/parsing/test_amber.py

This PR addresses issue #272. 
This issue exposed a nasty bug inside the regex pattern we used to extract sections in the amber output file.
we are trying to match a sequence of type
filed = int/float
extracting the int/float corresponding to the field. Up till now, the pattern was 
```python
fr' {field}\s+=\s+(\*+|{_FP_RE}|\d+)'
```
were `field` was the string we want to extract the value for, and `_FP_RE` is defined to extract the float/int after the equal.
The problem arises when the field and/or the value are not separated from the `=` sign by a space (as was the case in the issue). It's strange this didn't appear before!
I just changed the `+` in `\s+=\s+` to `*`.
Thinking about it, this should not break anything else, but I can't be 100% sure and the tests should catch any "macro" …

AMBER parser had a "too strict" regex to extract values

---

CHANGES
src/alchemlyb/tests/test_workflow.py
src/alchemlyb/workflows/abfe.py
src/alchemlyb/workflows/base.py

In https://github.com/alchemistry/flamel/issues/24, it is reported that when the output directory didn't exist, the flow will crash. This PR make it that if the output directory didn't exist, it will be created.

Make output directory when it didn't exist for workflow

---

CHANGES
src/alchemlyb/preprocessing/subsampling.py
src/alchemlyb/tests/test_preprocessing.py

Fix the dE method for AMBER

---

CHANGES
src/alchemlyb/workflows/abfe.py

Ok, I got it to work now by changing `glob.glob` to `Path.glob`, these two should be the same but `Path.glob` works fine.
I tried 
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple alchemlyb=="2.0.1"
and then
pytest --pyargs alchemlyb
Where all tests passed fine.

309 make pip test work in m1 mac

---

CHANGES
devtools/conda-envs/test_env.yaml
docs/parsing.rst
docs/parsing/alchemlyb.parsing.parquet.rst
environment.yml
setup.py
src/alchemlyb/parsing/parquet.py
src/alchemlyb/tests/parsing/test_parquet.py
src/alchemlyb/tests/test_workflow_ABFE.py
src/alchemlyb/workflows/abfe.py

This PR add a parquet parser, which will load the serialised dataframe and permits the usage of
```
from alchemlyb.parsing.parquet import extract_dHdl, extract_u_nk
import pandas as pd
u_nk.to_parquet(path='u_nk.parquet', index=True)
dHdl.to_parquet(path='dHdl.parquet', index=True)
new_u_nk = extract_u_nk('u_nk.parquet', T=300)
new_dHdl = extract_dHdl('dHdl.parquet', T=300) 
```
Fix https://github.com/alchemistry/alchemlyb/issues/316

parquet parser for dataframe serialisation

---

CHANGES
src/alchemlyb/parsing/amber.py
src/alchemlyb/tests/parsing/test_amber.py

ValueError will be raised if concatenated amber output file has been ingested

---

docs/workflows/alchemlyb.workflows.base.rst

Gromacs, as written, returns an error: "NotImplementedError: Gromacs parser not found."

capitalize GROMACS in documentation code example

---

CHANGES
docs/index.rst

- fix #369
- once this is fixed, we can update the JOSS paper draft PR #328 to only mention SPEC 0

adopt SPEC 0 instead of NEP 29

---

CHANGES
devtools/conda-envs/test_env.yaml
environment.yml
setup.py
src/alchemlyb/visualisation/ti_dhdl.py

Fix https://github.com/alchemistry/flamel/issues/28

Support matplotlib 3.9.0

---

CHANGES
README.md
docs/index.rst
docs/parsing.rst
docs/tutorial.rst
docs/visualisation.rst
docs/workflows/alchemlyb.workflows.ABFE.rst

Fix #382 
- add link to docs in README
- add tutorial section to docs
See https://github.com/openjournals/joss-reviews/issues/6934 :
- providing a single example case with input file, e.g. simple example, e.g., a self-contained jupyter notebook, to walk through the main functionalities.
- add link to docs inside README

Add a tutorial section

---

AUTHORS
docs/.templates/footer.html
docs/conf.py

- fix #383
- replaced explicit (incomplete) author list in doc footer with The alchemlyb development team and a link to AUTHORS
- added @xiki-tempula to the top of AUTHORS (which brings the author file in line with the author list and acknowledgements of the JOSS paper PR #328 )

replace doc footer

---

joss_paper/paper.bib
joss_paper/paper.md

Fix #386
> Shuai Liu is missing ORCid
@shuail 
> Affiliations: some of the have zip codes, some of them dont
All zip code removed
> line 23-25 could be better with a general citation
Add merz2010drug
> line 81-84 could be better with a general citation
Add deng2009computations
> line 111 - you could remove the word 'doing'
Removed
> line 182 - is it un-equilibrated or non-equilibrated?
non-equilibrated
> line 198 - formatting for 'alchemlyb' is not there
Formatted
> line 221 - citation, please check DOI
Added.
> line 257 - citation, please recheck DOI
This is a book and I cannot find a DOI
> line 271 - citation, please recheck DOI
Added
> line 293 - citation, please recheck DOI
Book, cannot find DOI
> some journal names are abbreviations, some are full, could you please make them …

Minor changes to the paper

---

.github/workflows/ci.yaml
CHANGES
setup.py

Prepare for 2.3.2

---

CHANGES

- fix  #388
- corrected remaining wrong date to be MM/DD/YYYY format
(all other ones were corrected in 8d3dabcd3c9d2371e5ef8358bf9bef1239cd40dd )
- make format clearer in top message
- reformatting (line length, spaces)

fixed one remaining wrong date in CHANGES

---

CITATION.cff

- close #402
- use same title in CITATION.cff for paper and project (required for the JOSS paper publication #71)
- added DOI for preferred citation in note because that is the only hint that shows up on zenodo)

make zenodo archive title identical to JOSS paper title

---

docs/tutorial.rst

replace `pandas.concat()` with `alchemlyb.concat()` in the tutorial (given that we explicitly tell users to use it)

[doc] tutorial: use alchemlyb.concat

---

docs/visualisation.rst

The function plot_convergence() expects a pandas dataframe as the single argument in the current implementation, causing it to fail when passed 4 different lists as arguments instead. This edit corrects the tutorial to appropriately pass a single dataframe with the appropriate column names, resulting in code that successfully reproduces the example graph.  
This should resolve issue #421.

correct error in tutorial for plot_convergence()

---

CHANGES
src/alchemlyb/estimators/bar_.py
src/alchemlyb/estimators/base.py
src/alchemlyb/estimators/mbar_.py
src/alchemlyb/parsing/__init__.py
src/alchemlyb/postprocessors/units.py
src/alchemlyb/tests/test_fep_estimators.py

Add enthalpy and entropy outputs for MBAR and BAR (via 2-state MBAR).

Add entropy and enthalpy
