.coveragerc, .travis.yml, README.rst, src/alchemlyb/tests/test_import.py, src/alchemlyb/tests/test_placeholder.py
[Alchemlyb TravisCI Panel](https://travis-ci.org/alchemistry/alchemlyb)
Python Versions:
* 2.7
Branches:
* master
* develop (not a major branch yet)
=> Enable continuous integration with TravisCI

docs/parsing.rst, docs/parsing/alchemlyb.parsing.amber.rst, src/alchemlyb/parsing/amber.py
=> include parsing.amber docs

src/alchemlyb/preprocessing/subsampling.py, src/alchemlyb/tests/test_preprocessing.py
- Fixes #39.
- Closes PR #38 
Notes:
- **merge** this PR (do not rebase)
=> change subsampling with statistical_inefficiency() (#39)

src/alchemlyb/tests/parsing/test_gmx.py, src/alchemlyb/tests/parsing/test_util.py
Moved tests specific to parsing utilities to their own test module.
=> Created parsing/test_util

docs/parsing/alchemlyb.parsing.gmx.rst
Added brief documentation on GROMACS expanded ensemble data parsing.
=> Issue 49: add documentation for GMX EE parsing

src/alchemlyb/tests/parsing/test_gmx.py
I found a weird line of code that looks like a typo to me.
=> Fix test_u_nk

src/alchemlyb/parsing/amber.py, src/alchemlyb/parsing/gmx.py, src/alchemlyb/tests/parsing/test_amber.py, src/alchemlyb/tests/test_fep_estimators.py, src/alchemlyb/tests/test_ti_estimators.py
- fix #57 (TI parser)
- fix #56 (FEP parser)
=> Amber parsers use kT units

setup.py, src/alchemlyb/parsing/namd.py, src/alchemlyb/tests/parsing/test_namd.py, src/alchemlyb/tests/test_fep_estimators.py
fix #75 
- move NAMD FEP test from parsing to test_fep
- take T as argument
=> make NAMD parser return energies in kT

src/alchemlyb/tests/test_fep_estimators.py, src/alchemlyb/tests/test_ti_estimators.py
- fix #88 
- made TI test code more similar in structure to FEP test code
=> Faster ti fixtures 88

AUTHORS, CHANGES
- close #83
- close #84
- files were manually created based on the history (git log --format="format:%an %ad" --date="format:%Y" 0.1.0..HEAD | sort | uniq)
and the merged PRs and closed issues
=> add AUTHORS and CHANGES

.gitignore, CHANGES, docs/conf.py, docs/estimators/alchemlyb.estimators.BAR.rst, docs/estimators/alchemlyb.estimators.MBAR.rst, docs/estimators/alchemlyb.estimators.TI.rst, docs/parsing/alchemlyb.parsing.amber.rst, docs/parsing/alchemlyb.parsing.gmx.rst, docs/parsing/alchemlyb.parsing.gomc.rst, docs/parsing/alchemlyb.parsing.namd.rst, docs/preprocessing/alchemlyb.preprocessing.subsampling.rst, docs/visualisation/alchemlyb.visualisation.plot_convergence.rst, docs/visualisation/alchemlyb.visualisation.plot_dF_state.rst, docs/visualisation/alchemlyb.visualisation.plot_mbar_overlap_matrix.rst, docs/visualisation/alchemlyb.visualisation.plot_ti_dhdl.rst, setup.py
- close #136 
- release a 0.4.2 from this branch (after it is merged)
=> fix online docs

.travis.yml, CHANGES, docs/index.rst, setup.py
- close #140
- drop Python 3.6
- require pandas >= 1.2
- update setp.py metadata
- update CHANGES
- updated docs (add note to Development Model)
=> adopt NEP29

docs/index.rst
=> Update the mission

AUTHORS, CHANGES, src/alchemlyb/preprocessing/subsampling.py, src/alchemlyb/tests/test_preprocessing.py
=> Change order of series vs. data check

CHANGES, docs/estimators/alchemlyb.estimators.MBAR.rst, src/alchemlyb/estimators/__init__.py, src/alchemlyb/estimators/mbar_.py, src/alchemlyb/tests/test_fep_estimators.py
=> implement auto mbar 

CHANGES, src/alchemlyb/parsing/amber.py
- log to module logger and not the root logger
- removed redundant ERROR and WARNING text
- removed redundant trailing newlines
=> fixed AMBER parser logging

CHANGES, src/alchemlyb/convergence/convergence.py, src/alchemlyb/tests/test_convergence.py
=> Add autombar to the convergence analysis list

CHANGES, README.rst, docs/conf.py, docs/install.rst
fix #192 
Add missing docs for conda installation
- update README
- update sphinx docs
=> [DOC] conda installation

src/alchemlyb/parsing/amber.py, src/alchemlyb/parsing/gmx.py, src/alchemlyb/parsing/gomc.py, src/alchemlyb/preprocessing/subsampling.py, src/alchemlyb/tests/test_preprocessing.py
=> Fix all the pandas warnings

src/alchemlyb/parsing/amber.py
Addressing issue #226, I removed the useless extraction of dHdl averages (and dHdl components at the same time).
PS: I also made a really small adjustment to the ```skip_lines``` method of ```SectionParser```, as it stated it skipped a given number of "files" (????) while it should obviously be "lines" :-)
=> Removed extraction of dHdl avg and components in AMBER parser

CHANGES, src/alchemlyb/parsing/amber.py
Here I just addressed issue #229. 
It doesn't change much, but the #FIXME bothered me :-)
=> addressing #FIXME and #NOTE about reading integers/float while parsing files

src/alchemlyb/workflows/abfe.py
=> Update the ABFE doc to make it more clear

src/alchemlyb/visualisation/convergence.py, src/alchemlyb/visualisation/dF_state.py, src/alchemlyb/visualisation/ti_dhdl.py
To partially address what emerged in issue #244
=> Edited the docs to clarify `units` behavior

CHANGES
For release 1.0.1, #279.
Note that this is a patch release so any Enhancements listed are internal and do NOT affect user-facing code. They are only improving code quality and ability to maintain.
=> finalized CHANGELOG

CHANGES
=> finalize for release 2.0.0

docs/workflows/alchemlyb.workflows.ABFE.rst
=> Fix the docs

CHANGES
@orbeckst I have finalised the changelog, is there any other thing that I need to change?
=> Prepare 2.0.1

src/alchemlyb/tests/test_workflow_ABFE.py, src/alchemlyb/workflows/abfe.py
=> Change the documentation to make the behaviour of dir in ABFE pipeline more clear

CHANGES, src/alchemlyb/parsing/amber.py, src/alchemlyb/visualisation/convergence.py, src/alchemlyb/visualisation/dF_state.py, src/alchemlyb/visualisation/ti_dhdl.py, src/alchemlyb/workflows/abfe.py
=> Correct the old style logging.

joss_paper/paper.bib, joss_paper/paper.md
I've also reordered the middle authors as indicated. A bunch of accented letters were added in the process. I hope it's Unicode all the way down... If that causes trouble in the PDF build, I'll switch to LaTeX escape sequences.
=> Add JH to author lists, extra reference

joss_paper/paper.md
Also fixes Ian's orcid field entry.
The paper looks great! No changes I can offer at this time.
=> Add Irfan Alibay to paper.md

joss_paper/paper.md
@orbeckst @xiki-tempula, please review. Thanks again for including me. Looking forward to catching up one of these days; it has been too many moons.
=> Add affiliation

src/alchemlyb/tests/parsing/test_amber.py, src/alchemlyb/tests/parsing/test_gmx.py, src/alchemlyb/tests/parsing/test_gomc.py, src/alchemlyb/tests/parsing/test_namd.py, src/alchemlyb/tests/test_fep_estimators.py, src/alchemlyb/tests/test_preprocessing.py, src/alchemlyb/tests/test_ti_estimators.py, src/alchemlyb/tests/test_ti_gaussian_quadrature.py
I have no idea why GMX failed, I have downgraded scipy, numpy and pandas to version before that but still cannot reproduce the old result. Consider that the difference is small, I think we shall just correct the test.
=> Fix GMX test
